
#static is here mvpland_static
#postgresql -- mvpland
#username -- cfedeploy
#password -- ##


"""
Django settings for ecommerce2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

from django.conf import settings
import dj_database_url

if not settings.DEBUG:
	import os

# add this

	BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	#root of project

	# Quick-start development settings - unsuitable for production
	# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

	# SECURITY WARNING: keep the secret key used in production secret!
	SECRET_KEY = 'csqwlmc8s55o($rt6ozh7u+ui9zb-et00w$d90j8$^!nvj41_r'

	# SECURITY WARNING: don't run with debug turned on in production!
	DEBUG = False

	ADMINS = (
		("diogo", "diogo.ds62@gmail.com"),

		)

	ALLOWED_HOSTS = ['https://multi-ecommerce.herokuapp.com/']
	#purchasing domain name http://name.com

	EMAIL_HOST = 'smtp.gmail.com'
	EMAIL_HOST_USER = 'panggolim@gmail.com'
	EMAIL_HOST_PASSWORD = 'Di728560@@'
	EMAIL_PORT = 587
	EMAIL_USE_TLS = True

	DEFAULT_FROM_EMAIL = [("Panggolim <panggolim@gmail.com>")]
	MANAGERS=ADMINS

	'''
	If using gmail, you will need to
	unlock Captcha to enable Django
	to  send for you:
	https://accounts.google.com/displayunlockcaptcha
	'''



	# Application definition

	INSTALLED_APPS = (
	    #django app
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.sites',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    #third party apps
	    'crispy_forms',
	    'registration',
		'django_filters',
	    #my apps
		'newsletter',
		'products',
		'carts',
		'orders',
		'sellers',
	)

	MIDDLEWARE_CLASSES = (
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'django.middleware.security.SecurityMiddleware',
	)

	ROOT_URLCONF = 'ecommerce2.urls'

	TEMPLATES = [
	    {
	        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	        'DIRS': [os.path.join(BASE_DIR, "templates")],
	        'APP_DIRS': True,
	        'OPTIONS': {
	            'context_processors': [
	                'django.template.context_processors.debug',
	                'django.template.context_processors.request',
	                'django.contrib.auth.context_processors.auth',
	                'django.contrib.messages.context_processors.messages',
	            ],
	        },
	WSGI_APPLICATION = 'ecommerce2.wsgi.application'


	# Database
	# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

	from .db_password import DBPASS

	DATABASES = {
	    'default': {
	        'ENGINE': 'django.db.backends.postgresql_psycopg2',
	        'NAME': "test",
	        'USER': "diogo",
	        'PASSWORD': dbpass,
	    }
	}


	# Internationalization
	# https://docs.djangoproject.com/en/1.8/topics/i18n/

	LANGUAGE_CODE = 'en-us'

	TIME_ZONE = 'UTC'

	USE_I18N = True

	USE_L10N = True

	USE_TZ = True


	# Static files (CSS, JavaScript, Images)
	# https://docs.djangoproject.com/en/1.8/howto/static-files/

	STATIC_URL = '/static/'

	MEDIA_URL = '/media/'

	ALLOWED_HOSTS = ['*']

	STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

	MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

	db_from_env = dj_database_url.config(conn_max_age=500)
	DATABASES['default'].update(db_from_env)

	#Crispy FORM TAGs SETTINGS
	CRISPY_TEMPLATE_PACK = 'bootstrap3'


	#DJANGO REGISTRATION REDUX SETTINGS
	ACCOUNT_ACTIVATION_DAYS = 7
	REGISTRATION_AUTO_LOGIN = True
	SITE_ID = 1
	LOGIN_REDIRECT_URL = '/'


	#BRAINTREE PAYMENTS DETAILS

	BRAINTREE_PUBLIC = "6rhmcym3ppvggbrq"
	BRAINTREE_PRIVATE = "db78285aa54368a5c299ccf62f0f0530"
	BRAINTREE_MERCHAND_ID = "kkj4x5y4nq5msn5r"
	BRAINTREE_ENVIRONMENT = "sandbox"

	# AWS
	STATICFILES_LOCATION = 'static'
	MEDIAFILES_LOCATION = 'media'

	AWS_S3_SECURE_URLS = True
	AWS_QUERYSTRING_AUTH = False
	AWS_PRELOAD_METADATA = True
	AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
	AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = 'multi-ecommerce'
	AWS_S3_CUSTOM_DOMAIN = 's3.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME

	STATICFILES_STORAGE = 'djangoecommerce.s3util.StaticStorage'
	STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)

	DEFAULT_FILE_STORAGE = 'djangoecommerce.s3util.MediaStorage'
	MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)

	AWS_HEADERS = {
		'x-amz-acl': 'public-read',
		'Cache-Control': 'public, max-age=31556926'
	}

    # Thumbnails
    THUMBNAIL_ALIASES = {
        '': {
            'product_image': {'size': (285, 160), 'crop': True},
        },
    }
    THUMBNAIL_DEFAULT_STORAGE = DEFAULT_FILE_STORAGE

try:
    from .local import *
except ImportError:
    pass